language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U coverage mock nose pylint pyyaml setuptools
  - pip install -U coveralls
script:
  - chmod a-x seqparse/test/*.py
  - python setup.py install
  - bash seqparse/test/ci-run_tests
after_success:
  - coveralls
