language: python
python:
  - "2.7"
install:
  - pip install -U pyyaml scandir setuptools
  - pip install -U coveralls
script:
  - chmod a-x seqparse/test/*.py
  - python setup.py install
  - bash seqparse/test/ci-run_tests
after_success:
  - coveralls
