#!/bin/bash

pp=$(dirname $(dirname $(readlink -f $0)))
export PYTHONPATH=${pp}/python:$PYTHONPATH

nosetests -v -s tests --with-xunit --all-modules --traverse-namespace \
  --cover-erase --cover-html --with-coverage --cover-inclusive --with-id

python -m coverage xml --include=seqparse*

pylint -d I0011,R0204,R0801 seqparse \
  --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' \
  > pylint.out
