#!/bin/bash

nosetests -v -s seqparse --with-xunit --all-modules --traverse-namespace \
  --cover-erase --cover-html --with-coverage --cover-inclusive --with-id

EXIT_STATUS=$?

pylint -d I0011,R0204,R0801 seqparse \
  --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}]'

exit ${EXIT_STATUS}
