#!/bin/bash

pp=$(dirname $(dirname $(readlink -f $0)))
export PYTHONPATH=${pp}:$PYTHONPATH

nosetests -v -s seqparse --all-modules --cover-erase --cover-html \
  --cover-package=seqparse --traverse-namespace --exe --with-coverage \
  --cover-inclusive --with-id --with-xunit

python -m coverage xml --include=seqparse*

pylint -d I0011,I0012,R0204,R0801 seqparse \
  --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' \
  > pylint.out
