#!/bin/bash

pp=$(dirname $(dirname $(readlink -f $0)))
export PYTHONPATH=${pp}:$PYTHONPATH

nosetests -v

python -m coverage xml --include=seqparse*

pylint -d I0011,I0012,R0204,R0801,W0622 seqparse \
  --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' \
  > pylint.out
